site:
  title: 'Podman Maven Plugin - Documentation'
content:
  sources:
    - url: .
      branches [ master ]
      start_path: docs
asciidoc:
  attributes:
    page-pagination: ''
    idprefix: ''
    idseparator: '-'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./docs/supplemental-ui
